# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-10 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170529_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='days',
        ),
        migrations.AddField(
            model_name='course',
            name='day',
            field=models.ManyToManyField(related_name='courses', through='api.Class', to='api.Day'),
        ),
        migrations.AlterField(
            model_name='class',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='api.Day'),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(max_length=9),
        ),
    ]
